Шаблонизируй это
htmlacademy-ecmascript/822295-big-trip-13 pull request #4
Opened 2020-11-26 08:10 UTC by dariapek

2020-11-27 14:27 UTC, rideorgtfo requested changes
В папке mock из названий файлов нужно убрать слово mock, оно избыточно

2020-11-27 14:27 UTC, rideorgtfo commented on src/view/edit-form.js
> +  const tripType = isCreateForm ? TRIP_TYPES[getRandomInteger(0, TRIP_TYPES.length - 1)] : type;
Зачем тут рандомное значение?

2020-11-27 14:27 UTC, rideorgtfo commented on src/view/point.js
> +  const day = 86400000;
Опционально можно написать так:
```
  const second = 1000;
  const minute = 60 * second;
  const hour = 60 * minute;
  const day = 24 * hour;
```
И нужно вынести за функцию

2020-11-27 14:27 UTC, rideorgtfo commented on src/view/point.js
> +};
Твое условие
```
(hour - minute) >= diff
```
сломается на времени 59минут и 1 секунда. Это тоже меньше часа.
Можно сделать вот так
```
if (diff < hour) {

} else if (diff < day) {

} else {

}
```

2020-11-27 14:27 UTC, rideorgtfo commented on src/view/point.js
> +  const offer = OFFERS.find((offerItem) => offerItem.id === offerId);
OFFERS лучше передавать снаружи. Представь что у тебя в одном месте приложения будут одни опции, а в другом другие? Ты не сможешь переиспользовать эту функцию в таком виде.

2020-11-27 16:50 UTC, dariapek commented
> В папке mock из названий файлов нужно убрать слово mock, оно избыточно

Я понимаю, но я это сделала для своего удобства. Я думаю этот момент не принципиален, так как эта папка будет удалена.

2020-11-27 17:28 UTC, dariapek commented on src/mock/trip-point-mock.js
> +    offerIds: [getRandomItemFromArray(OFFERS).id],
Да

2020-11-27 17:33 UTC, dariapek commented on src/view/edit-form.js
> +  const tripType = isCreateForm ? TRIP_TYPES[getRandomInteger(0, TRIP_TYPES.length - 1)] : type;
Чтобы значение менялось

2020-11-27 22:03 UTC, rideorgtfo commented on src/view/edit-form.js
> +  const tripType = isCreateForm ? TRIP_TYPES[getRandomInteger(0, TRIP_TYPES.length - 1)] : type;
Не стоит смешивать данные и представление. Давай их разделим

2020-11-27 22:04 UTC, rideorgtfo commented on src/mock/trip-point-mock.js
> +    offerIds: [getRandomItemFromArray(OFFERS).id],
Но их может быть несколько вместе. Давай сделаем функцию возвращающую рандомное количество. Например от одного до трех

2020-11-30 08:09 UTC, dariapek commented on src/view/edit-form.js
> +  const tripType = isCreateForm ? TRIP_TYPES[getRandomInteger(0, TRIP_TYPES.length - 1)] : type;
Не совсем понимаю, как разделить. Мб просто в этом случае выводить первый элемент массива TRIP_TYPES?

2020-11-30 15:23 UTC, rideorgtfo commented on src/view/edit-form.js
> +  const tripType = isCreateForm ? TRIP_TYPES[getRandomInteger(0, TRIP_TYPES.length - 1)] : type;
Давай сделаем параметр у функции ```defaultTripType```. Там же можешь сделать значение по-умолчанию.
А если хочешь случайное - вычисляй его в другом месте и передавай параметром

2020-11-30 15:35 UTC, rideorgtfo commented on src/mock/trip-point-mock.js
> +    .join(``);
Ты удаляешь элементы исходного массива. Для второго вызова может не остаться значений.

У предложений не случайный порядок

Лучшим алгоритмом здесь будет следующий:
1. Клонируем массив, дальше работаем с копией
2. Берем рандомный элемент
3. Удаляем его из массива, остается массив меньшего на 1 размера
4. Если недостаточно элементов идем в п.2

2020-11-30 15:35 UTC, rideorgtfo commented on src/mock/trip-point-mock.js
> +  return offers.map((offer) => offer.id).splice(minCount, maxCount);
Предположу что ты перепутала ```splice``` и ```slice```. Вторым аргументов splice передается количество элементов для удаления.

Если хочешь получить рандомные элементы массива без повторений см. алгоритм выше

2020-11-30 15:52 UTC, dariapek commented on src/mock/trip-point-mock.js
> +    .join(``);
То есть ```
descriptions
    .map((description) => description)
    .splice(randomElement, 1)
    .join(``);
```

2020-12-01 13:38 UTC, merged